services:
  code-server:
    image: aisflow/code:latest
    container_name: code-server
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./config:/home/code/.config"
      - "./home:/home/code/project/home"
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
