services:
  code-server:
    image: aisflow/code:latest
    container_name: code-server
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./config:/home/coder/.config"
      - "./home:/home/coder/project"
    stdin_open: true
    tty: true
