#!/bin/bash
set -e

# Define colors
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

setup_user() {
    UID="${UID:-1001}"
    GID="${GID:-1001}"
    UNAME="${USERNAME:-code}"
    # Set ownership of the home directory
    echo -e "${GREEN}Setting ownership of home directory for ${UNAME}...${NC}"
    chown -r "${UID}:${GID}" "/home/${UNAME}"
    echo -e "${GREEN}Ownership set successfully for ${UNAME}!${NC}"
}

if [ "$(id -u)" -eq 0 ]; then
    setup_user  # Call the setup_user function
    fc-cache -f -v
    exec gosu "${UNAME}" code-server --bind-addr 0.0.0.0:8080 .
else
    exec "$@"  # If not root, execute the command directly
fi