#!/bin/bash

set -e

for d in "$@"; do
    find "${d}" \
        ! \( \
            -group "${USER}" \
            -a -perm -g+rwX \
        \) \
        -exec chgrp "${USER}" -- {} \+ \
        -exec chmod g+rwX -- {} \+
    find "${d}" \
        \( \
            -type d \
            -a ! -perm -6000 \
        \) \
        -exec chmod +6000 -- {} \+
done